version: '3'
services:
  go:
    build: ./backend
    tty: true
    container_name: back
    volumes:
      - .:/common_tasks
    ports:
      - 8080:8080

  vue:
    build: ./vue-test-project
    tty: true
    container_name: front
    volumes:
      - .:/common_tasks
    ports:
      - 3001:3001

  db:
    image: postgres:13.11
    container_name: psql
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Pasona123
volumes:
  db-store:
