version: '3'
services:
  go:
    build: .
    tty: true
    container_name: go
    volumes:
      - .:/common_tasks
    ports:
      - 3000:3000

  db:
    image: postgres:13.11
    container_name: psql
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Pasona123
volumes:
  db-store:

